#!/usr/bin/env sh

key="$1"
coPath=$(dirname $(realpath ${BASH_SOURCE[0]}))
if [[ ! -f $coPath/recipes/$key.sh ]]
then
  echo "Error: Application unavailable.\n"
  echo "Available applications:"
  recipes=$(ls $coPath/recipes)
  echo "$recipes" | sed -E 's/(.*)\.sh/ \1\\/' | xargs echo ""
  exit 1
fi

bash $coPath/recipes/$key.sh $(pwd) ${@:2}
